[build]
  command = "npm run build:ci"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[dev]
  framework = "create-react-app"
  targetPort = 3000
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
